name: Auto Feature/Fix Branch Build

on:
  push:
    branches:
      - 'MT-**'

env:
  AC_USER: Warm_App
  AC_APP_ANDROID: android_prod
  AC_APP_IOS: ios_production
  CONFIG_BRANCH: feature-branch-config

jobs:
  run-build-on-appcenter:
    name: Feature/Fix Branch Build
    runs-on: ubuntu-latest
    steps:
      - uses: nicolascavallin/appcenter-config-build
        with:
          user: ${{ env.AC_USER }}
          app: ${{ env.AC_APP_ANDROID }}
          workbranch: ${{ github.ref }}
          configbranch: ${{ env.CONFIG_BRANCH }}
          token: ${{ secrets.APP_CENTER_ACCESS_TOKEN }}
