name: Auto Feature/Fix Branch Build

on:
  push:
    branches:
      - 'MT-**'

env:
  AC_USER: Warm_App2
  AC_APP_ANDROID: android_prod
  AC_APP_IOS: ios_production
  CONFIG_BRANCH: feature-branch-config

jobs:
  run-build-on-appcenter:
    name: Feature/Fix Branch Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Build
        id: appcenter-build
        uses: ./.github/actions/appcenter
        with:
          appcenter_user: ${{ env.AC_USER }}
          appcenter_app: ${{ env.AC_APP_IOS }}
          branch_name: ${{ github.ref_name }}
          settings_branch_name: ${{ env.CONFIG_BRANCH }}
          appcenter_token: ${{ secrets.APP_CENTER_ACCESS_TOKEN }}

      - name: Run Yarn Lint
        id: yarn-lint
        run: yarn lint

      - name: Echo Yarn Lint
        if: always() && steps.yarn-lint.outcome == 'failure'
        run: |
          CODE=`curl --write-out '%{http_code}' \
              --silent \
              --output /dev/null \
              --request PATCH \
              --header 'accept: application/json' \
              --header 'Content-Type: application/json' \
              --header 'X-API-Token: ${{ secrets.APP_CENTER_ACCESS_TOKEN }}' \
              --url 'https://api.appcenter.ms/v0.1/apps/${{ env.AC_USER }}/${{ env.AC_APP_ANDROID }}/builds/${{ steps.appcenter-build.outputs.build_id }}' \
              --data '{ 
                "status": "cancelling"
              }'`
