name: Feature/Fix Branch Build

on: workflow_dispatch

jobs:
  build:
    name: Feature/Fix Branch Build
    runs-on: ubuntu-latest

    steps:
      - name: Clone repository
        uses: actions/checkout@v2
