name: Feature/Fix Branch Build

on:
  workflow_dispatch:
    inputs:
      branch:
        description: 'Branch to build'
        required: true

env:
  BRANCH: ${{ inputs.branch }}
  AC_USER: Warm_App
  AC_APP: android_prod

jobs:
  run-build-on-appcenter:
    name: Feature/Fix Branch Build
    runs-on: ubuntu-latest

    steps:
      - name: Check if exists config for the branch on AppCenter
        id: check-config
        run: |
          CODE=`curl --write-out '%{http_code}' -X 'GET' \
            'https://api.appcenter.ms/v0.1/apps/${{ env.AC_USER }}/${{ env.AC_APP }}/branches/${{ env.BRANCH }}/config' \
            -H 'accept: application/json' \
            -H 'X-API-Token: ${{ secrets.APP_CENTER_ACCESS_TOKEN }}' \
            -H 'Content-Type: application/json'`

          if [ $CODE = 200 ] || [ $CODE = 404 ]
          then
            echo $CODE
            echo "::set-output name=code::$CODE"
          else
            echo "CAN'T CHECK IF EXISTS CONFIG"
            exit 1
          fi

      - name: Set config for the branch on AppCenter
        if: ${{ steps.check-config.outputs.code == 404 }}
        id: set-config
        run: |
          CODE=`curl --write-out '%{http_code}' -X 'POST' \
            'https://api.appcenter.ms/v0.1/apps/${{ env.AC_USER }}/${{ env.AC_APP }}/branches/${{ env.BRANCH }}/config' \
            -H 'accept: application/json' \
            -H 'X-API-Token: ${{ secrets.APP_CENTER_ACCESS_TOKEN }}' \
            -H 'Content-Type: application/json' \
            -d '{
              "cloneFromBranch": "main"
            }'`

          if [ $CODE = 200 ]
          then
            echo $CODE
            echo "::set-output name=code::$CODE"
          else
            echo "CAN'T CHECK IF EXISTS CONFIG"
            exit 1
          fi

      - name: Run Android build on AppCenter
        id: android-build
        run: |
          CODE=`curl --write-out '%{http_code}' -X 'POST' \
            'https://api.appcenter.ms/v0.1/apps/${{ env.AC_USER }}/${{ env.AC_APP }}/branches/${{ env.BRANCH }}/builds' \
            -H 'accept: application/json' \
            -H 'X-API-Token: ${{ secrets.APP_CENTER_ACCESS_TOKEN }}' \
            -H 'Content-Type: application/json'`        

          if [ $CODE = 200 ]
          then
            echo $CODE
            echo "::set-output name=code::$CODE"
          else
            echo "CAN'T RUN BUILD ON APPCENTER"
            exit 1
          fi
