name: Feature/Fix Branch Build

on: workflow_dispatch

env:
  BRANCH: $GITHUB_REF_NAME
  AC_USER: Warm_App
  AC_APP: android_prod

jobs:
  run-build-on-appcenter:
    name: Feature/Fix Branch Build
    runs-on: ubuntu-latest

    steps:
      - name: Branch name
        run: echo running on branch $GITHUB_REF_NAME

      - name: Check if exists config for the branch on AppCenter
        id: check-config
        run: |
          CODE=`curl --write-out '%{http_code}' \
              --silent \
              --output /dev/null \
              --request GET \
              --header 'accept: application/json' \
              --header 'X-API-Token: ${{ secrets.APP_CENTER_ACCESS_TOKEN }}' \
              --url 'https://api.appcenter.ms/v0.1/apps/${{ env.AC_USER }}/${{ env.AC_APP }}/branches/${{ env.BRANCH }}/config'`

          if [ $CODE = 200 ] || [ $CODE = 404 ]
          then
            echo $CODE
            echo "::set-output name=code::$CODE"
          else
            echo "CAN'T CHECK IF EXISTS CONFIG"
            exit 1
          fi

      - name: Check outputs
        run: echo ${{ steps.check-config.outputs.code }}

      - name: Conditional 200
        if: ${{ steps.check-config.outputs.code == 200 }}
        run: echo "BRANCH EXISTS"

      - name: Conditional 404
        if: ${{ steps.check-config.outputs.code == 404 }}
        run: echo "BRANCH DOESN'T EXISTS"
