name: Feature/Fix Branch Build

on: workflow_dispatch

env:
  BRANCH: ${{ github.ref_name }}
  AC_USER: Warm_App
  AC_APP: android_prod

jobs:
  run-build-on-appcenter:
    name: Feature/Fix Branch Build
    runs-on: ubuntu-latest

    steps:
      - name: Branch name
        run: echo running on branch $GITHUB_REF_NAME

      - name: Build Android
        run: |
          CODE=`curl --write-out '%{http_code}' \
              --silent \
              --output /dev/null \
              --request GET \
              --header 'accept: application/json' \
              --header 'X-API-Token: ${{ secrets.APP_CENTER_ACCESS_TOKEN }}' \
              --url 'https://api.appcenter.ms/v0.1/apps/${{ env.AC_USER }}/${{ env.AC_APP }}/branches/${{ env.BRANCH }}/config'`

          echo $CODE
