name: Feature/Fix Branch Build

on: workflow_dispatch

jobs:
  build:
    name: Feature/Fix Branch Build
    runs-on: ubuntu-latest

    steps:
      - name: Branch name
        run: echo running on branch ${GITHUB_REF##*/}
