name: New Build

on: workflow_dispatch

jobs:
  prepare-build:
    runs-on: ubuntu-latest
    steps:
      - name: View context attributes
        uses: actions/github-script@v6
        with:
          script: console.log("${{ secrets.ANDROID_ALIAS }}")

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Run Lint
        run: yarn lint:fix
