name: Release Build

on:
  workflow_dispatch:
    inputs:
      target:
        type: choice
        description: 'Version bump'
        required: true
        options:
          - patch
          - minor
          - major
          - hotfix
          - prerelease

env:
  BRANCH: dev
  AC_USER: Warm_App
  AC_APP_ANDROID: android_prod
  AC_APP_IOS: ios_production
  CONFIG_BRANCH: feature-branch-config
  VERSION: ${{ inputs.target == 'hotfix' && 'prerelease' || inputs.target }}
  TAG: ${{ inputs.target == 'hotfix' && 'hotfix' || 'latest' }}

jobs:
  prepare-build:
    name: Feature/Fix Branch Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2
        with:
          ref: ${{ env.BRANCH }}

      - name: Bump version
        id: bump-version
        run: |
          yarn global add np
          git config --global user.email "hello@holded.com"
          git config --global user.name "GitHub Actions Bot"
          yarn np --any-branch ${{ env.VERSION }} --branch ${{ env.BRANCH }} --tag="${{ env.TAG }}"
