name: Release Build

on:
  workflow_dispatch:
    inputs:
      target:
        type: choice
        description: 'Version bump (if you are not sure, check http://google.com/RELEASE.md)'
        default: prerelease
        required: true
        options:
          - patch
          - minor
          - major
          - hotfix
          - prerelease
          - prepatch
          - preminor
          - premajor

env:
  GH_TOKEN: ${{ github.token }}
  BRANCH: dev
  AC_USER: Warm_App
  AC_APP_ANDROID: android_prod
  AC_APP_IOS: ios_production
  CONFIG_BRANCH: feature-branch-config
  VERSION: ${{ inputs.target == 'hotfix' && 'prerelease' || inputs.target }}
  COMMIT: ${{ inputs.target == 'hotfix' && 'hotfix' || ( inputs.target == 'prerelease' || inputs.target == 'prepatch' || inputs.target == 'preminor' || inputs.target == 'premajor' ) && 'prerelease' || 'release' }}

jobs:
  prepare-build:
    name: Feature/Fix Branch Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2
        with:
          ref: ${{ env.BRANCH }}

      - name: Bump version
        id: bump-version
        run: |
          yarn global add np
          git config --global user.email "hello@holded.com"
          git config --global user.name "${{ github.triggering_actor }}"
          yarn np --any-branch --no-tests ${{ env.VERSION }} --branch ${{ env.BRANCH }} --message="${{ env.COMMIT }} v%s"
          NEW_VERSION=`jq .version package.json` | sed "s/\"//g"
          gh pr create --base main --head ${{ env.BRANCH }} --title="${{ env.COMMIT }} $NEW_VERSION" --body="${{ env.COMMIT }} $NEW_VERSION"
